import test from 'node:test';
import assert from 'node:assert/strict';
import {createDocument,validateDocument,DocumentStore,makeNode,defaultTextStyle,Camera,SpatialIndex,hitNode,worldPoint,localPoint,bounds,intersects,preflight,color,clone} from '../src/core.js';
import {createDemo} from '../src/demo.js';
const fixture=()=>{const d=createDocument();const n=makeNode('rect',d.pages[0].id);d.nodes.push(n);return {d,n};};
const storyFrame=(d,id,text,opts={})=>{d.stories['story-'+id]={text};const n=makeNode('text',d.pages[0].id,{id,storyId:'story-'+id,style:{...defaultTextStyle},...opts});d.nodes.push(n);return n;};
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
test('empty document schema is valid',()=>assert.equal(validateDocument(createDocument()).version,1));
test('editorial sample validates and contains six real pages',()=>{const d=validateDocument(createDemo());assert.equal(d.pages.length,6);assert.ok(d.nodes.length>30);assert.equal(Object.keys(d.assets).length,2);});
test('sample stories have a valid thread',()=>{const d=createDemo(),n=d.nodes.find(n=>n.nextId);assert.equal(d.nodes.find(t=>t.id===n.nextId).storyId,n.storyId);});
test('document rejects empty page collection',()=>{const d=createDocument();d.pages=[];assert.throws(()=>validateDocument(d));});
test('document rejects nonfinite geometry',()=>{const {d,n}=fixture();n.x=NaN;assert.throws(()=>validateDocument(d));});
test('document rejects negative dimensions',()=>{const {d,n}=fixture();n.h=-1;assert.throws(()=>validateDocument(d));});
test('document rejects duplicate object ids',()=>{const {d,n}=fixture();d.nodes.push(clone(n));assert.throws(()=>validateDocument(d));});
test('document rejects broken page references',()=>{const {d,n}=fixture();n.pageId='missing';assert.throws(()=>validateDocument(d));});
test('document rejects broken layer references',()=>{const {d,n}=fixture();n.layerId='missing';assert.throws(()=>validateDocument(d));});
test('document rejects untrusted object IDs',()=>{const {d,n}=fixture();n.id='x" onclick="alert(1)';assert.throws(()=>validateDocument(d));});
test('document rejects color attribute injection',()=>{const {d,n}=fixture();n.fill='#000000" onload="alert(1)';assert.throws(()=>validateDocument(d));});
test('document rejects script image sources',()=>{const d=createDocument();d.assets.evil={name:'x',src:'javascript:alert(1)'};assert.throws(()=>validateDocument(d));});
test('document rejects external tracking image sources',()=>{const d=createDocument();d.assets.evil={name:'x',src:'https://example.test/pixel.png'};assert.throws(()=>validateDocument(d));});
test('document permits embedded raster assets',()=>{const d=createDocument();d.assets.ok={name:'x',src:'data:image/png;base64,YQ=='};assert.doesNotThrow(()=>validateDocument(d));});
test('document rejects margins that consume the page',()=>{const d=createDocument();d.settings.margin=500;assert.throws(()=>validateDocument(d));});
test('one gesture is one undo transaction',()=>{const {d,n}=fixture(),s=new DocumentStore(d);s.begin('drag');for(let i=0;i<50;i++)n.x++;s.commit();assert.equal(s.undoStack.length,1);assert.equal(n.x,110);});
test('undo restores document before a gesture',()=>{const {d,n}=fixture(),s=new DocumentStore(d);s.transact('move',()=>n.x=400);s.undo();assert.equal(s.getNode(n.id).x,60);});
test('redo restores document after a gesture',()=>{const {d,n}=fixture(),s=new DocumentStore(d);s.transact('move',()=>n.x=400);s.undo();s.redo();assert.equal(s.getNode(n.id).x,400);});
test('new transaction clears redo branch',()=>{const {d,n}=fixture(),s=new DocumentStore(d);s.transact('move',()=>n.x=400);s.undo();s.transact('edit',()=>s.getNode(n.id).x=80);assert.equal(s.redoStack.length,0);});
test('no-op transactions do not grow history',()=>{const {d}=fixture(),s=new DocumentStore(d);s.transact('nothing',()=>{});assert.equal(s.undoStack.length,0);});
test('cancel rolls back an in-progress gesture',()=>{const {d,n}=fixture(),s=new DocumentStore(d);s.begin('drag');n.x=999;s.cancel();assert.equal(s.getNode(n.id).x,60);assert.equal(s.undoStack.length,0);});
test('failed validation is atomic',()=>{const {d,n}=fixture(),s=new DocumentStore(d);assert.throws(()=>s.transact('invalid',()=>n.w=-1));assert.equal(s.getNode(n.id).w,180);assert.equal(s.undoStack.length,0);});
test('exceptions inside a transaction roll back',()=>{const {d,n}=fixture(),s=new DocumentStore(d);assert.throws(()=>s.transact('throws',()=>{n.x=400;throw Error('test');}));assert.equal(s.getNode(n.id).x,60);});
test('nested transactions are rejected',()=>{const {d}=fixture(),s=new DocumentStore(d);s.begin('outer');assert.throws(()=>s.begin('inner'));s.cancel();});
test('history is count-bounded',()=>{const {d,n}=fixture(),s=new DocumentStore(d);for(let i=0;i<100;i++)s.transact('move',()=>n.x++);assert.equal(s.undoStack.length,80);});
test('duplicate creates independent node geometry',()=>{const {d,n}=fixture(),s=new DocumentStore(d);const ids=s.duplicateNodes([n.id]);assert.equal(ids.length,1);assert.notEqual(ids[0],n.id);assert.equal(s.getNode(ids[0]).x,n.x+12);});
test('duplicate text has an independent story',()=>{const d=createDocument(),a=storyFrame(d,'a','Hello'),s=new DocumentStore(d),ids=s.duplicateNodes([a.id]);assert.notEqual(s.getNode(ids[0]).storyId,a.storyId);});
test('text linking combines stories',()=>{const d=createDocument(),a=storyFrame(d,'a','First'),b=storyFrame(d,'b','Second'),s=new DocumentStore(d);s.linkFrames(a.id,b.id);assert.equal(a.nextId,b.id);assert.equal(a.storyId,b.storyId);assert.equal(d.stories[a.storyId].text,'First\nSecond');});
test('text linking rejects self reference',()=>{const d=createDocument(),a=storyFrame(d,'a','First'),s=new DocumentStore(d);assert.throws(()=>s.linkFrames(a.id,a.id));});
test('text linking rejects cyclic thread',()=>{const d=createDocument(),a=storyFrame(d,'a','First'),b=storyFrame(d,'b','Second'),s=new DocumentStore(d);s.linkFrames(a.id,b.id);assert.throws(()=>s.linkFrames(b.id,a.id));});
test('import validation rejects cyclic thread',()=>{const d=createDocument(),a=storyFrame(d,'a','First'),b=storyFrame(d,'b','Second');b.storyId=a.storyId;a.nextId=b.id;b.nextId=a.id;assert.throws(()=>validateDocument(d));});
test('deleting a linked target removes incoming reference',()=>{const d=createDocument(),a=storyFrame(d,'a','First'),b=storyFrame(d,'b','Second'),s=new DocumentStore(d);s.linkFrames(a.id,b.id);s.deleteNodes([b.id]);assert.equal(a.nextId,null);assert.equal(d.nodes.length,1);});
test('camera roundtrip preserves world coordinates',()=>{const c=new Camera();c.x=130;c.y=-80;c.zoom=.73;const p=c.toScreen(-30,400),q=c.toWorld(p.x,p.y);near(q.x,-30);near(q.y,400);});
test('zoom preserves cursor anchor',()=>{const c=new Camera();c.x=42;c.y=100;c.zoom=.5;const before=c.toWorld(510,230);c.zoomAt(510,230,2.7);const after=c.toWorld(510,230);near(before.x,after.x);near(before.y,after.y);});
test('zoom is clamped at supported bounds',()=>{const c=new Camera();c.zoomAt(0,0,10000);assert.equal(c.zoom,8);c.zoomAt(0,0,.000001);assert.equal(c.zoom,.08);});
test('fit contains an entire spread',()=>{const c=new Camera();c.fit({x:0,y:0,w:1200,h:800},1000,800,50);near(c.zoom,.75);near(c.x,50);near(c.y,100);});
test('rotated node local/world transforms are inverses',()=>{const {n}=fixture();n.rotation=37;const p=worldPoint(n,31,82),q=localPoint(n,p.x,p.y);near(q.x,31);near(q.y,82);});
test('rotated geometry is hit in local coordinates',()=>{const {n}=fixture();n.rotation=80;const p=worldPoint(n,60,40);assert.ok(hitNode(n,p.x,p.y));const q=worldPoint(n,-50,40);assert.equal(hitNode(n,q.x,q.y),false);});
test('ellipse hit testing excludes bounding-box corners',()=>{const {n}=fixture();n.type='ellipse';assert.equal(hitNode(n,n.x,n.y),false);assert.ok(hitNode(n,n.x+n.w/2,n.y+n.h/2));});
test('rotated bounds include all corners',()=>{const {n}=fixture();n.rotation=45;const b=bounds(n);for(const [x,y]of [[0,0],[180,0],[180,120],[0,120]]){const p=worldPoint(n,x,y);assert.ok(p.x>=b.x-1e-8&&p.x<=b.x+b.w+1e-8);assert.ok(p.y>=b.y-1e-8&&p.y<=b.y+b.h+1e-8);}});
test('spatial index returns frontmost objects first',()=>{const {d,n}=fixture(),other=makeNode('rect',d.pages[0].id),index=new SpatialIndex();index.rebuild([n,other]);assert.equal(index.point(n.pageId,100,100)[0].id,other.id);});
test('spatial index separates pages',()=>{const {d,n}=fixture(),other=makeNode('rect',d.pages[1].id),index=new SpatialIndex();index.rebuild([n,other]);assert.equal(index.point(n.pageId,100,100).length,1);});
test('layer visibility removes artwork from ordered page scene',()=>{const {d,n}=fixture(),s=new DocumentStore(d);d.layers[0].visible=false;assert.equal(s.nodesOnPage(n.pageId).length,0);});
test('locked layers are not selectable',()=>{const {d,n}=fixture(),s=new DocumentStore(d);d.layers[0].locked=true;assert.equal(s.selectable(n),false);});
test('preflight detects overset terminal frames',()=>{const d=createDocument(),n=storyFrame(d,'a','text');const issues=preflight(d,new Map([[n.id,{overflow:true}]]));assert.equal(issues[0].severity,'error');});
test('preflight detects a missing image',()=>{const d=createDocument();d.nodes.push(makeNode('image',d.pages[0].id));assert.match(preflight(d)[0].message,/Missing image/);});
test('preflight detects low effective resolution',()=>{const d=createDocument();d.assets.a={name:'tiny',src:'data:image/png;base64,YQ==',width:50,height:50};d.nodes.push(makeNode('image',d.pages[0].id,{assetId:'a',w:200,h:200}));assert.match(preflight(d)[0].message,/resolution/);});
test('rectangle intersection includes touching edges',()=>assert.ok(intersects({x:0,y:0,w:10,h:10},{x:10,y:5,w:5,h:5})));
test('color conversion preserves channels and transparency',()=>{assert.deepEqual(color('#ff8000',.5),[1,128/255,0,.5]);assert.deepEqual(color('none'),[0,0,0,0]);});
