import { createDocument, makeNode, defaultTextStyle, uid } from './core.js';
export function createDemo() {
    const d = createDocument({ name: 'FORM — The Architecture Issue', pages: 6 });
    d.assets.architecture = { name: 'Quiet monument / original artwork', src: './assets/architecture.webp', width: 1400, height: 2000 };
    d.assets.detail = { name: 'Arcade study / original artwork', src: './assets/detail.webp', width: 1800, height: 1000 };
    const W = d.settings.width, H = d.settings.height;
    const add = (page, type, v) => { const n = makeNode(type, d.pages[page].id, v); d.nodes.push(n); return n; };
    const text = (page, name, value, x, y, w, h, style = {}) => { const sid = uid('story'); d.stories[sid] = { text: value }; return add(page, 'text', { name, x, y, w, h, layerId: 'type', storyId: sid, style: { ...defaultTextStyle, ...style } }); };
    const rule = (page, x, y, w, fill = '#6d7464') => add(page, 'rect', { name: 'Editorial rule', x, y, w, h: .6, fill, layerId: 'guides' });
    d.pages.forEach(p => p.background = '#f4f1e8');
    add(0, 'image', { name: 'Cover image', x: 0, y: 0, w: W, h: H, assetId: 'architecture', fit: 'cover' });
    text(0, 'Masthead', 'form.', 40, 32, 440, 146, { fontSize: 130, color: '#f8f5eb', leading: 1, tracking: -7 });
    text(0, 'Issue line', 'A JOURNAL OF SPACE, OBJECT & CULTURE', 44, 180, 520, 24, { fontFamily: 'Arial', fontSize: 10, tracking: 2.7, color: '#f8f5eb' });
    text(0, 'Cover headline', 'The art of\nless.', 45, 563, 485, 184, { fontSize: 81, leading: 1.04, color: '#f8f5eb', tracking: -2 });
    text(0, 'Edition', 'ISSUE 008   /   AUTUMN 2026', 46, 786, 495, 20, { fontFamily: 'Arial', fontSize: 10, tracking: 2, color: '#f8f5eb' });
    add(1, 'image', { name: 'Quiet monument', x: 0, y: 0, w: W, h: H, assetId: 'architecture', fit: 'cover' });
    text(1, 'Running title', 'F O R M    /    ARCHITECTURE', 39, 31, 420, 22, { fontFamily: 'Arial', fontSize: 9, fontWeight: '700', tracking: 1.2, color: '#f8f5eb' });
    text(1, 'Feature title', 'The shape\nof silence.', 39, 620, 520, 160, { fontSize: 69, leading: 1.02, color: '#fffbed', tracking: -2.2, paragraphSpace: 0 });
    text(1, 'Feature caption', 'A study in light, material, and everything in between.', 42, 779, 510, 23, { fontSize: 11, italic: true, color: '#f4f0e2' });
    text(1, 'Folio left', '02', 42, 815, 30, 15, { fontFamily: 'Arial', fontSize: 8, color: '#fffbed' });
    text(2, 'Section label', 'SPACES  /  THE CONSIDERED LIFE', 46, 38, 500, 24, { fontFamily: 'Arial', fontSize: 9, tracking: 1.8, fontWeight: '700', color: '#68715b' });
    rule(2, 46, 71, 503, '#8d927f');
    text(2, 'Display headline', 'Less, but\nmore meaning.', 42, 97, 520, 170, { fontSize: 64, leading: 1.04, tracking: -2.5, color: '#343e2e', paragraphSpace: 0 });
    text(2, 'Introduction', 'In a world that never stops adding, we find\nbeauty in what is left out.', 46, 287, 500, 64, { fontSize: 20, leading: 1.36, tracking: -.25, color: '#637056', paragraphSpace: 0 });
    rule(2, 46, 373, 48, '#6a755a');
    text(2, 'Author', 'WORDS BY THE FORM EDITORS', 111, 367, 418, 24, { fontFamily: 'Arial', fontSize: 8, fontWeight: '700', tracking: 1.3, color: '#737867' });
    const body = 'There is a particular kind of quiet that only architecture can create. Not the absence of sound, but a feeling of having arrived. A pause. A room that asks nothing of you except to be present.\nWe look for it in the places we inhabit: in a wall warmed by the afternoon sun, the generous curve of an arch, the gentle weight of an honest material.\nThese spaces are not empty. They are intentional. Every surface, opening and shadow has been considered, then allowed to breathe. What remains is not less life, but more room for it.';
    text(2, 'Editorial body', body, 46, 414, 503, 220, { fontSize: 12, leading: 1.55, columns: 2, gutter: 25, paragraphSpace: 8, balanceColumns: true });
    add(2, 'image', { name: 'Arcade detail', x: 46, y: 647, w: 503, h: 119, assetId: 'detail', fit: 'cover' });
    text(2, 'Image caption', '01 — A conversation between light and solid form.', 46, 778, 470, 18, { fontFamily: 'Arial', fontSize: 8.5, color: '#7f8475' });
    rule(2, 46, 807, 503, '#b0b3a5');
    text(2, 'Footer journal', 'FORM JOURNAL', 46, 817, 320, 14, { fontFamily: 'Arial', fontSize: 7, tracking: 1.7, color: '#6c7562' });
    text(2, 'Folio right', '03', 524, 815, 26, 17, { fontFamily: 'Arial', fontSize: 9, color: '#343e2e', align: 'right' });
    text(3, 'Section label', 'OBJECTS  /  MATERIAL MATTERS', 44, 40, 510, 25, { fontFamily: 'Arial', fontSize: 9, tracking: 2, color: '#68715b' });
    text(3, 'Feature title', 'Built to\nbelong.', 40, 91, 515, 167, { fontSize: 78, leading: 1.02, tracking: -3 });
    add(3, 'image', { name: 'Arcade study', x: 44, y: 300, w: 507, h: 356, assetId: 'detail', fit: 'cover' });
    text(3, 'Quote', '“A building should feel as though\nit has always been there.”', 44, 691, 505, 90, { fontSize: 25, italic: true, leading: 1.3, color: '#647055' });
    text(3, 'Folio', '04', 44, 812, 45, 18, { fontFamily: 'Arial', fontSize: 9 });
    text(4, 'Section label', 'ESSAY  /  AN ARCHITECTURE OF CARE', 44, 40, 520, 25, { fontFamily: 'Arial', fontSize: 9, tracking: 1.8, color: '#68715b' });
    text(4, 'Essay headline', 'A slower\nway of seeing.', 40, 92, 520, 177, { fontSize: 63, leading: 1.08, tracking: -2 });
    const long = body + '\n' + body;
    const first = text(4, 'Essay · first frame', long, 44, 301, 243, 463, { fontSize: 12, leading: 1.65 });
    const second = text(4, 'Essay · continuation', '', 309, 301, 242, 463, { fontSize: 12, leading: 1.65 });
    second.storyId = first.storyId;
    first.nextId = second.id;
    rule(4, 44, 798, 507);
    text(4, 'Folio', '05', 518, 812, 35, 20, { fontFamily: 'Arial', fontSize: 9, align: 'right' });
    d.pages[5].background = '#354230';
    text(5, 'Back masthead', 'form.', 42, 64, 510, 149, { fontSize: 130, leading: 1, color: '#ebe9db', tracking: -6 });
    text(5, 'Back statement', 'Good spaces.\nBetter stories.', 47, 572, 502, 146, { fontSize: 52, leading: 1.12, color: '#ebe9db', tracking: -1 });
    text(5, 'Back footer', 'INDEPENDENT PERSPECTIVES. CONSIDERED DESIGN.', 48, 787, 520, 22, { fontFamily: 'Arial', fontSize: 8, tracking: 1.5, color: '#d3d8c4' });
    return d;
}
